name: Deploy Python Lambda Function

on:
  pull_request:
    branches:
      - 'develop'
    types:
      - closed
    paths:
      - DailySiteDistributor/**

jobs:
  deploy-lambda:
    uses: ./.github/workflows/deploy-lambda-reusable.yml
    with:
      lambda-function-name: MonthlyAddingSiteTablesProducer
      lambda-dir: DailySiteDistributor
      aws-account-id: '683918607581'
      github-oidc-role: HeatmapJapan-GithubAction
      deployment-message: 'Producer Lambda deployment successful!'
