name: Deploy Monthly Adding Site Tables Consumer Lambda

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'
    types:
      - closed
    paths:
      - MonthlyAddingSiteTablesConsumer/**

jobs:
  deploy-lambda:
    uses: ./.github/workflows/deploy-lambda-reusable.yml
    with:
      lambda-function-name: MonthlyAddingSiteTablesConsumer
      lambda-dir: MonthlyAddingSiteTablesConsumer
      aws-account-id: '683918607581'
      github-oidc-role: HeatmapJapan-GithubAction
      deployment-message: 'Consumer Lambda deployment successful!'
